# Numpy portfolio part zero

note: After spending a considerable amount of time on insufficient learning, this marks my initial official attempt at learning Numpy. hoping this time I keep learning untill some reasonble resualts!

### so what is numpy afterall? 

basically, it has alot to do with arrays. to be more precies about that, numpy (short for Numerical Python,) is a python library used primarily for working with array. very famouse in linear algebra and matrices. 

---
getting started with numpy: making simple arrays:

In [3]:
import numpy as np

In [4]:
x = np.array([0, 1, 2, 3, 4])
x

array([0, 1, 2, 3, 4])

In [5]:
type(x)

numpy.ndarray

the *ndarray* means n-dimentional array.

In [6]:
y = np.array([[0, 1, 2], [3, 4, 5]])
y

array([[0, 1, 2],
       [3, 4, 5]])

the probable bettwe way to write down more-than-one dimentional arrays are like below:

In [7]:
z = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

as mentioned above, the type() indicates that x, y and z are n-dim arrays. how to see how many dims do they got? here is the answer:

In [8]:
z.ndim

2

---

#### what do you know about dimention?
The first axis represents the rows, and the second axis represents the columns. so that is a 2 dimentional array!
what about more-dimentional arrays? how to make those?
the short and simple answer is to count the number of nested ([]) in an array() instance. below is a 3 dimentional array:

In [9]:
x = np.array([[[0, 1, 2],
               [3, 4, 5],
               [6, 7, 8]],
              
              [[9, 10, 11],
              [12, 13, 14],
              [15, 16, 17]],
              
             [[18, 19, 20],
              [21, 22, 23],
              [24, 25, 25]]
             ])
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 25]]])

In [10]:
x.ndim

3

#### how to check how many row or column or others an array has? 
easily, with .shape.

In [11]:
x.shape

(3, 3, 3)

#### how to see the total count of an array elemnts?
easily, with .size.

In [12]:
x.size

27

(by the way, I just got rejected from a data sience job I applied. moving on... )

---

#### Fun different arrays in numpy
just see below to feel the magic:

In [13]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
x = np.ones((5, 5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
x = np.zeros((5, 5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

---

#### is there a way to create those arrays faster?
NumPy *arange()* is one of the array creation routines based on numerical ranges. It creates an instance of ndarray with evenly spaced values and returns the reference to it.
here is the schema for its parameters:
```python
numpy.arange([start, ]stop, [step, ], dtype=None) -> numpy.ndarray
```
don't get confused. read these examples below:

In [16]:
x = np.arange(0, 10, 3)
x

array([0, 3, 6, 9])

to show that better, here is what that above indicates:
```python
x = np.arange(start=0, end=10, step=3)
```

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x = np.arange(10, 3, -2)
x

array([10,  8,  6,  4])

In [19]:
x = np.arange(1, 2, 0.1)
x

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

---

#### question: is there a way to use arange to make more-than-one dimentional arrays?
answer: use *reshape()* to do that:

In [20]:
x = np.arange(6)
x = x.reshape((3, 2))
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
x = np.arange(0, 32, 2).reshape((4, 4))
x

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [22]:
np.reshape(x, (2, 8))

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26, 28, 30]])

---

#### a quick question: what are in-place or out-of-place functions?
consider this below:
```python
x.reshape((3, 2))
```
the one above, does not change anything on the array x. It just returns a new array, that has the desired changes. If you wish to use the new array, you could simply assign that to a new variable like below:
```python
reshaped_arr = x.reshape((3, 2))
```
so, the *reshape()* function is basically an **out-of-place** function. These functions do not modify the original array. Instead, they return a new array with the desired changes, leaving the original array untouched.
what about **in-shape** functions? These functions do modify the original array directly, meaning that the changes are reflected in the original array itself.
##### so, which type are the numpy functions?
Most NumPy functions are out-of-place by default. This is consistent with NumPy's design philosophy to ensure that the original data is preserved unless explicitly requested to be modified. This behavior is beneficial when you need to maintain the integrity of the original data, especially when working in scientific computing and data analysis, where preserving the original dataset is crucial.

##### what is inplace=true then?
some other libraries like Pandas, may have that 'inplace=true' in some function parameters, making them in-place functions rather than out-of-place ones.
consider this example?:
```python
df = pd.DataFrame({'A': [1, 2, 3]})
df.drop('A', axis=1, inplace=True)
```
that *inplace=true* parameter, makes sure that the changes appear in the original array. (not a copy of that.)

---

#### what are linear spaces and log spaces?
linear spaces, refers to a sequence of numbers that are evenly spaced between a specified starting point and an endpoint. here is how its parameters' posisined:
```python
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```
so, the default number=50

In [24]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [26]:
np.linspace(0, 9, 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

what about **log space**? numpy.logspace is a function in NumPy that generates numbers spaced evenly on a logarithmic scale. Instead of generating numbers evenly spaced in linear space (like linspace), logspace generates numbers that are evenly spaced in log space. This is useful when you need to create a sequence of values that grow (or shrink) exponentially.
```python
numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
```
above shows its parameters.

In [33]:
np.logspace(0, 9, num=10, base=2)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [32]:
np.logspace(0, 4, num=5, base=2)

array([ 1.,  2.,  4.,  8., 16.])

---

#### how to generate arrays with random numbers?
using random()! checkout examples below:

this **random.rand** generates a random array, with the numbers being its dims lenght.

In [38]:
np.random.rand(2, 4)   # a 2*4 random array.

array([[0.92159351, 0.5453029 , 0.87550607, 0.71707194],
       [0.78739933, 0.29737298, 0.94101626, 0.18362168]])

The **random.randint** is generates random integers, that has these parameters:
```python
random.randint(low, high=None, size=None, dtype=int)
```
consider this example:

In [41]:
np.random.randint(12, 20, 5)

array([18, 13, 13, 15, 16])

In [42]:
np.random.randint(0, 100)

42

---

### some basic math functions on arrays
#### Element-Wise Arithmetic
those could be some Element-Wise Arithmetic Operations like below:

In [44]:
x = np.array([0, 1, 2, 3])
x += 2
x

array([2, 3, 4, 5])

In [45]:
x *= 2
x

array([ 4,  6,  8, 10])

#### Aggregate Functions
those could also include Aggregate Functions like these:

In [47]:
np.sum(x)

28

In [48]:
np.mean(x)    # mean means the avarage

7.0

In [50]:
np.var(x)     # varians

5.0

In [51]:
np.std(x)     # standard deviation

2.23606797749979

#### rounding functions
Here are some cool rounding functions, that are assumed as math function:

In [52]:
np.floor([1.7, 2.3, 3.9])

array([1., 2., 3.])

In [53]:
np.ceil([1.7, 2.3, 3.9])

array([2., 3., 4.])

#### Trigonometric Functions

In [55]:
np.sin(x)

array([-0.7568025 , -0.2794155 ,  0.98935825, -0.54402111])

In [57]:
np.cos([90])

array([-0.44807362])

In [58]:
np.arcsin([1])

array([1.57079633])

#### Exponential and Logarithmic Functions

In [59]:
np.log(x)

array([1.38629436, 1.79175947, 2.07944154, 2.30258509])

In [60]:
np.log10(x)

array([0.60205999, 0.77815125, 0.90308999, 1.        ])

In [61]:
np.log2(x)

array([2.        , 2.5849625 , 3.        , 3.32192809])

### some basic Linear Algebra Operations
here are some basic matrix functions with numpy:

In [66]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

here is how to calculate the dot product of those two arrays

In [67]:
np.dot(a, b)

array([[13, 16],
       [40, 52],
       [67, 88]])

Matrix Multiplication:

In [68]:
np.matmul(a, b)

array([[13, 16],
       [40, 52],
       [67, 88]])

here is how to find the Transpose:

In [70]:
a.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

Determinant is calculated like below:

In [71]:
np.linalg.det(a)

0.0

Inverse:

In [77]:
# np.linalg.inv(a) since s has det of zero, then the inverse is not avalible.
c = np.random.rand(3, 3)
c

array([[0.41818683, 0.43004391, 0.62497456],
       [0.07399974, 0.9245735 , 0.55799839],
       [0.88583848, 0.65073641, 0.03314412]])

In [79]:
np.linalg.inv(c)

array([[ 0.8122956 , -0.95882826,  0.82550232],
       [-1.20169553,  1.31878148,  0.45713046],
       [ 1.88342151, -0.26587418, -0.86691588]])

---